
name: python program with dependancies
on:
    push:
        branches:
            - main

jobs:
    extract-data:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: install dependancy
              run: pip install -r requirements.txt
            - name: show python version
              run: python --version 
            - name: run python program
              run: extract_data.py