name: quality gate check

on:
  push:
    branches:
      - main

jobs:
  ci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run Tests and Generate Coverage Report
        run: |
          pytest --cov=calc \
                 --cov-report=term \
                 --cov-report=html \
                 --cov-fail-under=80

      - name: Upload HTML Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

  cd-job:
    runs-on: ubuntu-latest
    needs: ci-job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "deployment done..."